config/routes.rb
Movingbox::Application.routes.draw do
  resources :things

  resources :boxes

  match 'boxes/:id/print' => 'boxes#print', :as => :print_box

  

end

app/models/box.rb
class Box < ActiveRecord::Base
  attr_accessible :link, :name, :things_attributes

  has_many :things, :dependent => :destroy
  accepts_nested_attributes_for :things, :reject_if => lambda { |a| a[:desc].blank? }, :allow_destroy => true 

  image_accessor :qr_code


end

app/models/thing.rb
class Thing < ActiveRecord::Base
  attr_accessible :box_id, :desc, :things_attributes


  belongs_to :box
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boxes }
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @box = Box.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/1/print
  # GET /boxes/1/print.json
  def print
    @box = Box.find(params[:id])

    respond_to do |format|
      format.pdf { render :layout => false }
    end
  end

  # GET /boxes/new
  # GET /boxes/new.json
  def new
    @box = Box.new
    3.times { @box.things.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/1/edit
  def edit
    @box = Box.find(params[:id])
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(params[:box])

    respond_to do |format|
      if @box.save
        dest_url = url_for(:controller => 'boxes', :action => 'show', :id => @box.id ,:only_path => false)
        qr_code_img = RQRCode::QRCode.new(dest_url, :size => 4, :level => :h ).to_img.resize(300, 300)

        @box.update_attribute :qr_code, qr_code_img.to_string
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render json: @box, status: :created, location: @box }
      else
        format.html { render action: "new" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boxes/1
  # PUT /boxes/1.json
  def update
    @box = Box.find(params[:id])

    if @box.qr_code.nil?
      dest_url = url_for(:controller => 'boxes', :action => 'show', :id => @box.id ,:only_path => false)
      qr_code_img = RQRCode::QRCode.new(dest_url, :size => 4, :level => :h ).to_img.resize(300, 300)
      @box.update_attribute :qr_code, qr_code_img.to_string
    end
    respond_to do |format|
      if @box.update_attributes(params[:box])
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box = Box.find(params[:id])
    @box.destroy

    respond_to do |format|
      format.html { redirect_to boxes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  # GET /things
  # GET /things.json
  def index
    @things = Thing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @things }
    end
  end

  # GET /things/1
  # GET /things/1.json
  def show
    @thing = Thing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/new
  # GET /things/new.json
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(params[:thing])

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render json: @thing, status: :created, location: @thing }
      else
        format.html { render action: "new" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /things/1
  # PUT /things/1.json
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_remove_fields(name, f, options = {})
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)", options)
  end

  def link_to_add_fields(name, f, association, options = {})
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{ association }") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end

    link_to_function(name, "add_fields(this, \"#{ association }\", \"#{ escape_javascript(fields) }\")", options)
  end
 
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/application/_chromeframe.html.haml
/[if lt IE 7 ]
  %p.chromeframe
    You are using an <strong>outdated</strong> browser.
    Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>

app/views/application/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .wrapper
      %div{ :title => key.to_s.humanize, :class => key }
        %p= value

app/views/application/_footer.html.haml
%footer#footer
  %small.copyright
    Movingbox, Copyright &copy; #{ Date.today.year }

app/views/application/_head.html.haml
%head
  %meta{ :charset => "utf-8" }/

  -# Use the .htaccess and remove these lines to avoid edge case issues.
  -# More info: h5bp.com/b/378
  %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }/

  %title
    == #{ controller.controller_name.titleize } - #{ controller.action_name.titleize }

  %meta{ :name => "description", :content => "" }/

  -# Mobile viewport optimized: h5bp.com/viewport
  %meta{ :name => "viewport", :content => "width=device-width" }/

  -# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

  = render "stylesheets"

  -# More ideas for your <head> here: h5bp.com/d/head-Tips

  -# All JavaScript at the bottom, except polyfills
  = javascript_include_tag "polyfills"

  = csrf_meta_tag

app/views/application/_header.html.haml
%header#header
  %h1 Movingbox

app/views/application/_javascripts.html.haml
= javascript_include_tag "application"

-#  Append your own using content_for :javascripts
= yield :javascripts

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/html5_rails.yml
- if !google_account_id.blank?
  :javascript
    var _gaq=[['_setAccount','#{ google_account_id }'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/application/_stylesheets.html.haml
= stylesheet_link_tag 'application', :media => nil

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/boxes/_form.html.haml
= form_for @box do |f|
  - if @box.errors.any?
    #error_explanation
      %h2= "#{pluralize(@box.errors.count, "error")} prohibited this box from being saved:"
      %ul
        - @box.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  
  = f.fields_for :things do |builder|
    = render 'thing_fields', :f => builder

  %p
    = link_to_add_fields "Add thing", f, :things

  .actions
    = f.submit 'Save'

app/views/boxes/_thing_fields.html.haml
%p.fields
	= f.label :desc, "Content"
	= f.text_field :desc
	= link_to_remove_fields "remove", f

app/views/boxes/edit.html.haml
%h1 Editing box

= render 'form'

= link_to 'Show', @box
\|
= link_to 'Back', boxes_path

app/views/boxes/index.html.haml
%h1 Listing boxes

%table
  %tr
    %th Name
    %th Link
    %th
    %th
    %th

  - @boxes.each do |box|
    %tr
      %td= box.name
      %td= box.link
      %td= link_to 'Show', box
      %td= link_to 'Edit', edit_box_path(box)
      %td= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Box', new_box_path

app/views/boxes/new.html.haml
- content_for :stylesheets do 
  = stylesheet_link_tag 'boxes', :media => nil

%h1 New box

= render 'form'

= link_to 'Back', boxes_path

app/views/boxes/show.html.haml
%h2= @box.name

%p
  %h3 Contents
  %ul
    - @box.things.each do |thing|
      %li= thing.desc

%p
  -if !@box.qr_code.nil?
    =image_tag(@box.qr_code.url)

= link_to 'Edit', edit_box_path(@box)
\|
= link_to 'Back', boxes_path
\|
= link_to 'Print', print_box_path(@box,:format => 'pdf')

app/views/layouts/application.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
- html_tag :class => "no-js" do
  = render "head"

  %body{ :class => "#{ controller.controller_name }" }
    = render "chromeframe"
    = render "header"

    #main{ :role => "main" }
      = render "flashes"
      = yield

    = render "footer"

    -# Javascript at the bottom for fast page loading
    = render "javascripts"

app/views/things/_form.html.haml
= form_for @thing do |f|
  - if @thing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@thing.errors.count, "error")} prohibited this thing from being saved:"
      %ul
        - @thing.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :desc
    = f.text_field :desc
  .actions
    = f.submit 'Save'

app/views/things/edit.html.haml
%h1 Editing thing

= render 'form'

= link_to 'Show', @thing
\|
= link_to 'Back', things_path

app/views/things/index.html.haml
%h1 Listing things

%table
  %tr
    %th Box
    %th Desc
    %th
    %th
    %th

  - @things.each do |thing|
    %tr
      %td= thing.box_id
      %td= thing.desc
      %td= link_to 'Show', thing
      %td= link_to 'Edit', edit_thing_path(thing)
      %td= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Thing', new_thing_path

app/views/things/new.html.haml
%h1 New thing

= render 'form'

= link_to 'Back', things_path

app/views/things/show.html.haml
%p#notice= notice

%p
  %b Box:
  = @thing.box_id
%p
  %b Desc:
  = @thing.desc

= link_to 'Edit', edit_thing_path(@thing)
\|
= link_to 'Back', things_path